version: "2"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: sandbox/affiliate-platform
    # command: honcho start --procfile Procfile.dev
    volumes:
      - .:/app
    ports:
      - 8000:80
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
