version: "2"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: sandbox/affiliate-platform
    # command: honcho start --procfile Procfile.dev
    volumes:
      - .:/app
    ports:
      - 8000:80
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
