# Generated by Django 2.2.5 on 2019-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
