# Generated by Django 2.2.5 on 2019-10-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
