# Generated by Django 2.2.6 on 2020-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
