# Generated by Django 2.2.6 on 2020-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_trafficsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(to='offer.Category'),
        ),
    ]
