# Generated by Django 2.2.6 on 2020-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20200618_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='offer.Category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='traffic_sources',
            field=models.ManyToManyField(blank=True, through='offer.OfferTrafficSource', to='offer.TrafficSource'),
        ),
    ]
