# Generated by Django 2.2.6 on 2020-06-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('offer', '0010_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=7)),
                ('goal_value', models.CharField(default='1', max_length=20)),
                ('type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percent', 'Percent')], default='Fixed', max_length=20)),
                ('countries', models.ManyToManyField(to='countries_plus.Country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Currency')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Goal')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='offer.Offer')),
            ],
        ),
    ]
