# Generated by Django 2.2.6 on 2020-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Stopped', 'Stopped')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='tracking_link',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
