# Generated by Django 2.2.6 on 2020-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_auto_20200618_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='preview_link',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
