# Generated by Django 2.2.6 on 2020-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_offer_preview_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('contact_person', models.CharField(default='', max_length=64)),
                ('messenger', models.CharField(default='', max_length=64)),
                ('site', models.CharField(default='', max_length=64)),
                ('comment', models.TextField()),
            ],
        ),
    ]
