# Generated by Django 2.2.6 on 2020-06-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='advertiser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Advertiser'),
        ),
    ]
