# Generated by Django 3.0.7 on 2020-07-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_offer_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-id',)},
        ),
    ]
