# Generated by Django 3.0.7 on 2020-07-27 10:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_auto_20200726_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_html',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
