# Generated by Django 3.0.7 on 2020-09-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_offer_description_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=1024)),
                ('preview_url', models.CharField(default='', max_length=1024)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='offer.Offer')),
            ],
        ),
    ]
