# Generated by Django 3.0.7 on 2020-08-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0019_offer_description_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('created', 'Created'), ('not_found', 'Not Found'), ('approved', 'Approved'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='created', max_length=20)),
                ('goal', models.CharField(default='', max_length=20)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbacks', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postbacks', to='offer.Offer')),
            ],
        ),
    ]
