# Generated by Django 3.0.7 on 2020-08-26 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=500)),
                ('response_status', models.CharField(default='', max_length=10)),
                ('response_text', models.TextField()),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postback_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
