# Generated by Django 3.0.7 on 2020-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postback', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postback',
            name='goal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
