# Generated by Django 3.0.7 on 2020-10-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postback', '0003_auto_20200827_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postback',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('not_found', 'Not Found'), ('approved', 'Approved'), ('hold', 'Hold'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='created', max_length=20),
        ),
    ]
