# Generated by Django 2.2.6 on 2020-06-17 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliates', to=settings.AUTH_USER_MODEL),
        ),
    ]
