# Generated by Django 2.2.6 on 2020-06-17 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0004_auto_20191009_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('click_id', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_date', models.DateTimeField()),
                ('sub1', models.CharField(default='', max_length=500)),
                ('sub2', models.CharField(default='', max_length=500)),
                ('sub3', models.CharField(default='', max_length=500)),
                ('sub4', models.CharField(default='', max_length=500)),
                ('sub5', models.CharField(default='', max_length=500)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(default='', max_length=2)),
                ('ua', models.CharField(default='', max_length=200)),
                ('goal', models.CharField(default='', max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='rejected', max_length=10)),
                ('sum', models.FloatField(default=0.0)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='offer.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub1', models.CharField(default='', max_length=500)),
                ('sub2', models.CharField(default='', max_length=500)),
                ('sub3', models.CharField(default='', max_length=500)),
                ('sub4', models.CharField(default='', max_length=500)),
                ('sub5', models.CharField(default='', max_length=500)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(default='', max_length=2)),
                ('ua', models.CharField(default='', max_length=200)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=7)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='offer.Offer')),
            ],
        ),
    ]
