# Generated by Django 3.0.7 on 2020-06-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200618_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='goal',
            new_name='goal_value',
        ),
    ]
