# Generated by Django 3.0.7 on 2020-06-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_offer_advertiser'),
        ('tracker', '0003_auto_20200629_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Goal'),
        ),
    ]
