# Generated by Django 3.0.7 on 2020-06-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_offer_advertiser'),
        ('tracker', '0004_conversion_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Currency'),
        ),
    ]
