# Generated by Django 3.0.7 on 2020-06-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_conversion_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
