# Generated by Django 3.0.7 on 2020-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_conversion_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='click_id',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
    ]
