# Generated by Django 3.0.7 on 2020-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200803_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='click_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
