# Generated by Django 3.0.7 on 2020-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200803_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
