# Generated by Django 3.0.7 on 2020-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200803_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='ip',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
