# Generated by Django 3.0.7 on 2020-08-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20200803_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversion',
            options={'ordering': ('-created_at',)},
        ),
    ]
