# Generated by Django 3.0.7 on 2020-10-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20200914_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('hold', 'Hold'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='rejected', max_length=10),
        ),
    ]
